# Railway configuration file
# https://docs.railway.app/deploy/config-as-code

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
# No especificar startCommand - Railway usará el CMD del Dockerfile
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
