steps:
  # Build the container image from current directory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/$PROJECT_ID/registro-valorizaciones:$COMMIT_SHA', '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/registro-valorizaciones:$COMMIT_SHA']
    
  # Deploy container image to Cloud Run with environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'registro-valorizaciones'
    - '--image=gcr.io/$PROJECT_ID/registro-valorizaciones:$COMMIT_SHA'
    - '--region=southamerica-west1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8080'
    - '--memory=4Gi'
    - '--cpu=2'
    - '--timeout=900s'
    - '--max-instances=10'
    - '--set-env-vars=DEBUG=false'
    - '--set-env-vars=LOG_LEVEL=INFO'
    - '--set-env-vars=HOST=0.0.0.0'
    - '--set-env-vars=PORT=8080'
    - '--update-env-vars=NEON_CONNECTION_STRING=$(NEON_CONNECTION_STRING)'
    - '--update-env-vars=DATABASE_URL=$(NEON_CONNECTION_STRING)'

images:
  - 'gcr.io/$PROJECT_ID/registro-valorizaciones:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'
