name: Backend Integration Tests

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Optional run identifier for traceability
        required: false
        default: manual

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx requests

    - name: Run integration tests only
      run: |
        pytest -v -m "integration"
      env:
        PYTHONPATH: ${{ github.workspace }}
        NEON_CONNECTION_STRING: ${{ secrets.NEON_CONNECTION_STRING }}